### ISSUE TITLE
Aqara sensors support?

### ISSUE THREAD

**Issue by mvillarejo** [a4refillpad/Xiaomi#5]
Hello, this is an open question, have someone tested new aqara sensors with this scripts? I need to get more equipment and I'm considering buying a few. Cheers

**Comment by bspranger** [comment]
I have an Aqara Temperature/Humidity/Barometer and have it working.  I just put in a pull request to support the Barometer readings.

**Comment by mvillarejo** [comment]
The thing is that normal temp sensors didn't work properly for me, readings were kind of random for: temp, humidity and battery usage... couldn't figure out what was wrong, that's why I raised this: #3 Any idea what could be not working? thanks.

**Comment by mvillarejo** [comment]
It seems after latest version, they now properly work so this can be closed. 
I'll buy some of the new models soon. 

Thanks

**Comment by ghost** [comment]
> I have an Aqara Temperature/Humidity/Barometer and have it working. I just put in a pull request to support the Barometer readings.
